services:
  db:
    image: "autosdb"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata/custom/workingExampleData:/var/lib/postgresql/data
    env_file: "./.env"
  app:
    image: "interfaceapi"
    ports:
      - "8080:8080"
    env_file: "./.env"
    depends_on:
      - db
